### ISSUE TITLE
Uncaught RuntimeError: float unrepresentable in integer range

### ISSUE THREAD

**Issue by Haris487** [UmbraSoftware/umbrajs-three#3]
I had tried to integrate Umbra player.html example with potree.  And put animation code in potree loop function. But when it calls `Umbra.update()`. It throws an error.

`wasm-0012c2aa-212:1335 Uncaught RuntimeError: float unrepresentable in integer range
    at wasm-function[212]:2753
    at wasm-function[273]:446
    at Object.c._UmbraRuntimeUpdate (http://127.0.0.1:8000/aws/static/umbrajs-three/dist/umbrajs-three.js:2194:25)
    at Runtime.update (http://127.0.0.1:8000/aws/static/umbrajs-three/dist/umbrajs-three.js:3382:16)
    at UmbrajsThreeInternal.update (http://127.0.0.1:8000/aws/static/umbrajs-three/dist/umbrajs-three.js:4831:22)
    at updateUmbra (http://127.0.0.1:8000/aws/static/Potree/libs/potree/jsSnippets/initializationsSnippet.js:71:28)
    at PotreeRenderer.render (http://127.0.0.1:8000/aws/static/Potree/libs/potree/potree.js:20327:3)
    at PotreeViewer.loop (http://127.0.0.1:8000/aws/static/Potree/libs/potree/potree.js:20189:24)`

**Comment by Haris487** [comment]
This issue is resolved
